services:
  postgres:
    image: 'postgres:17.10-alpine3.24@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193'
    environment:
      POSTGRES_DB: '${POSTGRES_DB:-mydatabase}'
      POSTGRES_PASSWORD: '${POSTGRES_PW:?Set POSTGRES_PW before starting Compose}'
      POSTGRES_USER: '${POSTGRES_USER:?Set POSTGRES_USER before starting Compose}'
    ports:
      - '127.0.0.1:5432:5432'
  aistor:
    image: 'quay.io/minio/aistor/minio@sha256:17527b97a9e92dcc32b641dc161e4beb1eaf9a9198018c1489923c981f4af2ef'
    command: minio server /mnt/data --license /minio.license
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    volumes:
      - '${HOME}/minio/certs:/etc/minio/certs'
      - '${HOME}/minio/data:/mnt/data'
      - '${HOME}/minio/minio.license:/minio.license'
    tty: true
